version: "3.9"

services:
  bee-health-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bee-health-app:latest
    container_name: bee-health-app
    env_file:
      - ./docker/bee-health-app/env/bee-health-app.env
    environment:
      # 后端服务器的ip地址
      BASE_API_HOST: 192.168.86.131
    network_mode: host
