import Vue from 'vue'
import {
  Button,
  Tabbar,
  TabbarItem,
  Search,
  Grid,
  GridItem,
  Divider,
  DropdownMenu,
  DropdownItem,
  Icon,
  Col,
  Row,
  Sidebar,
  SidebarItem,
  NavBar,
  Area,
  Skeleton,
  List,
  Cell,
  Field,
  Form,
  CellGroup, Checkbox, PasswordInput, NumberKeyboard, Popup, Toast, Image as VanImage, Sticky, Tab, Tabs, SwipeCell, Tag, Swipe, SwipeItem, Lazyload, TreeSelect
} from 'vant'

Vue.use(Button)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Search)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Divider)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Icon)
Vue.use(Col)
Vue.use(Row)
Vue.use(Sidebar)
Vue.use(SidebarItem)
Vue.use(NavBar)
Vue.use(Area)
Vue.use(Skeleton)
Vue.use(List)
Vue.use(Cell)
Vue.use(Form)
Vue.use(Field)
Vue.use(CellGroup)
Vue.use(Checkbox)
Vue.use(PasswordInput)
Vue.use(NumberKeyboard)
Vue.use(Popup)
Vue.use(Toast)
Vue.use(VanImage)
Vue.use(Sticky)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(SwipeCell)
Vue.use(Tag)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Lazyload)
Vue.use(TreeSelect)
